version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data
    networks:
      - paxton_network

  auth-db:
    image: bitnami/postgresql:16.4.0
    container_name: auth_db
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=${KEYCLOAK_DB_USER_PASS}
      - POSTGRESQL_USERNAME=${KEYCLOAK_DB_USER}
      - POSTGRESQL_DATABASE=${KEYCLOAK_DB}
    networks:
      - paxton_network

  auth:
    image: bitnami/keycloak:26.0.5
    container_name: auth
    environment:
      KEYCLOAK_HOSTNAME_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_USER_PASS}
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: auth-db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DB_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DB_USER_PASS}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DB}
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_HEALTH_ENABLED: "true"
      KEYCLOAK_LOG_LEVEL: info
      KEYCLOAK_ENABLE_HEALTH_ENDPOINTS: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    ports:
      - "8081:8080"
      - "8441:8443"
    networks:
      - paxton_network
    depends_on:
      - auth-db
      - smtp

  smtp:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Europe/Bucharest
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - paxton_network

volumes:
  minio_storage: { }

networks:
  paxton_network:
    driver: bridge