### Spring main application properties ###
##
# Spring server configuration
# server.port=8080
server.ssl.enabled=false
# Allow Spring to lazy load beans
#spring.main.lazy-initialization=true
# Allow beans to be overridden with custom implementations
spring.main.allow-bean-definition-overriding=true
# Don't include stacktrace in server messages
server.error.include-stacktrace=never
# Disable Spring Boot start-up banner
spring.main.banner-mode=off
# Disable spring devtools for production environments
#spring.devtools.add-properties=false
######################
# JPA database connectivity
spring.datasource.url=jdbc:h2:file:./db/paxton-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
# Recreate the database upon application startup (only in dev/testing scenarios)
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
# And for production
# spring.jpa.hibernate.ddl-auto=none
# Liquibase properties
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/liquibase-changelog-master.xml
# H2 database
#spring.liquibase.url=jdbc:h2:file:./db/paxton-db
#spring.liquibase.user=sa
#spring.liquibase.password=password
# Postgres database
#spring.liquibase.url=jdbc:postgres:db/paxton_db
#spring.liquibase.user=postgres
#spring.liquibase.password=postgres_password
#spring.liquibase.change-log=classpath:db/changelog/postgres/liquibase-changelog-master.xml
#spring.liquibase.change-log=classpath:db/changelog/h2/liquibase-changelog-master.xml
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace
# Explicit naming strategy for the application
spring.jpa.hibernate.naming.physical-strategy=com.irb.paxton.config.db.PaxtonPhysicalNamingStrategy
# Defer the initialization of datasource
spring.jpa.defer-datasource-initialization=false
# Disable database queries during view renderings, as we are using external client
spring.jpa.open-in-view=false
######################
# Internalization
##
spring.messages.always-use-message-format=false
spring.messages.basename=src\main\resources\messages\validation
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true
######################
# Hibernate logging properties
##
#logging.level.org.hibernate.type=TRACE
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
######################
# Spring servlet properties
# Enable multipart requests, with max file size and request size
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
######################
# MVC routing patch matching strategy
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# Spring MVC logging
spring.mvc.log-resolved-exception=false
######################
# Spring mail properties
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
###################################################
### Tomcat embedded server configuration ###
##
server.tomcat.accesslog.enabled=true
# Tomcat logging properties
# logging.level.root=DEBUG
logging.level.org.apache.tomcat=INFO
logging.level.org.apache.catalina=INFO
##
###################################################
### Spring GraphQL properties ###
##
###################################################
logging.level.com.netflix.graphql.dgs.subscriptions.websockets=ERROR
### Paxton's application properties ###
##
# Security - Cross origin resource sharing properties
# Include http://localhost:3000 for local development
px.security.cors.allowedOrigins=http://localhost:${server.port},https://localhost:${server.port},http://localhost:3000
######################
###################################################
### Spring/Application Security properties ###
##
# Security - logging properties
# logging.level.org.springframework.security=DEBUG
###################################################
# Security - OAuth2 resource server properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/Paxton
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
# JWT Configuration
px.security.auth.jwt.resource-id=px-ui
px.security.auth.jwt.principal-attribute=preferred_username
# Keycloak instance
px.security.auth.keycloakUrl=http://localhost:8081
px.security.auth.keycloakRealm=Paxton
px.security.auth.keycloakClientId=px-ui
px.security.auth.keycloakAdminUser=px_admin
px.security.auth.keycloakAdminPassword=SDmiB6@5@J59@uMNdKYRdG
######################
######################
# Paxton SMTP email details extra
##
# Paxton SMTP email address
px.smtp.emailAddress=no-reply@paxton.org
# Paxton SMTP email From value, defaults to "Paxton Application"
px.smtp.emailFrom="Account Support - Paxton"
###################################################
### Paxton storage properties
##
#px.app.storage.minio-s3.enabled=true
px.app.storage.minio-s3.url=http://localhost:9000/
px.app.storage.minio-s3.access-key=jp5T3QnheJrwRq35
px.app.storage.minio-s3.secret-key=EPb6JErWy4DXDBqHHGxte9R79KT5j9XHyERgXkqGEWBu3s9LCkvabf38hd8wTrnK
# Paxton file name hashing
px.app.storage.saltValue=awd3!#dlkjpxt
######################
# Error handling starter
##
error.handling.http-status-in-json-response=true
error.handling.search-super-class-hierarchy=true
error.handling.full-stacktrace-http-statuses[0]=5xx
error.handling.messages.org.springframework.security.authentication.BadCredentialsException=Invalid username/password provided
##
error.handling.http-statuses.java.lang.IllegalArgumentException=bad_request
error.handling.http-statuses.org.springframework.web.bind.MethodArgumentNotValidException=bad_request
error.handling.http-statuses.jakarta.validation.ConstraintViolationException=bad_request
error.handling.http-statuses.org.springframework.security.access.AccessDeniedException=forbidden
###################################################