### H2
changeLogFile=src/main/resources/db/changelog/h2/liquibase-changelog-master.xml
outputChangeLogFile=src/main/resources/db/changelog/h2/liquibase-changelog-master.xml
diffChangeLogFile=src/main/resources/db/changelog/h2/${maven.build.timestamp}_changelog.xml
url=jdbc:h2:file:./db/paxton-db
driver=org.h2.Driver
referenceUrl=hibernate:spring:com.irb.paxton?dialect=liquibase.ext.hibernate.database.HibernateGenericDialect&hibernate.physical_naming_strategy=com.irb.paxton.config.db.PaxtonPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
referenceDbDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
username=sa
password=password

### Postgres
#changeLogFile=src/main/resources/db/changelog/h2/liquibase-changelog-master.xml
#outputChangeLogFile=src/main/resources/db/changelog/h2/liquibase-changelog-master.xml
#diffChangeLogFile=src/main/resources/db/changelog/h2/${maven.build.timestamp}_changelog.xml
#url=jdbc:h2:file:./db/paxton-db
#driver=org.h2.Driver
#referenceUrl=hibernate:spring:com.irb.paxton.core.location?dialect=liquibase.ext.hibernate.database.HibernateGenericDialect&hibernate.physical_naming_strategy=com.irb.paxton.config.db.PaxtonPhysicalNamingStrategy&hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#referenceDbDriver=liquibase.ext.hibernate.database.connection.HibernateDriver
#username=sa
#password=password