export enum PermissionType {
  READ_PRIVILEGE,
  WRITE_PRIVILEGE,
}

export enum RoleType {
  ROLE_ADMINISTRATOR = "ROLE_ADMINISTRATOR",
  ROLE_VIEWER = "ROLE_VIEWER",
  ROLE_RECRUITER = "ROLE_RECRUITER",
  ROLE_EVERYONE = "ROLE_EVERYONE",
}
