package com.irb.paxton.core.organization;

public enum Specialization {

    Banking,
    Retail_banking,
    Corporate_and_Investment_Banking,
    Private_Banking,
    Financial_services,
    Insurance,
    Securities_Services,
    Mobility,
    Credit,
    Entrepreneurs,
    Intrapreneurs,
    Commercial_Banking,
    Investment_Banking,
    Wealth_Management,
    Credit_Cards,
    Capital_Markets,
    Equity_and_Fixed_Income_Research,
    Consumer_Lending,
    Cash_Management,
    Transaction_Services,
    Offshore_Bonds,
    Investment_Funds,
    Equities_and_Brokerage,
    Exchange_Traded_Funds,
    Multi_Asset_Funds,
    Technology_Innovation,
    AI,
    Machine_Learning,
    Internet_of_Things,
    Blockchain,
    Virtual_Reality, Augmented_Reality,
    Software_Product_Design,
    Software_Development,
    Digital_Transformation,
    Financial_Software_Development,
    Insurtech_Development,
    Fintech_Development,
    Information_Technology_and_Services,
    IT_and_Software,
    Technical_Consulting,
    Project_Management,
    Information_Services,
    Engineering,
    Automotive,
    Industrial_Automation
}
